### ISSUE TITLE
make[1]: *** No rule to make target 'Image'.  Stop.;

### ISSUE THREAD

**Issue by Kra1v** [danascape/linux-oneplus-sm6350#1]
I tried to build lineage os 20 for my device(oneplus billie) and im getting some errors:

```
clang-14: error: unable to execute command: Executable "as" doesn't exist!
clang-14: error: assembler command failed with exit code 1 (use -v to see invocation);
make[1]: *** No rule to make target 'Image'.  Stop.;
make: *** [Makefile:148: sub-make] Error 2;
```

error log: https://pastebin.com/EMag3tJD

The clang error was solved by finding the "as" file in the source(lineage/external/clang/test/Driver/Inputs/basic_cross_linux_tree/usr/x86_64-unknown-linux-gnu/bin) and copying it to the folders that contain llvm-as.

But i have no idea how to solve "image" error.

**Comment by danascape** [comment]
Exclude the kernel from using latest LLVM, the kernel source needs additional patches

**Comment by Kra1v** [comment]
Thanks!
